feat(NOT-278): pnpm integration

diff --git a/.github/workflows/main.sonar.yml b/.github/workflows/main.sonar.yml
--- a/.github/workflows/main.sonar.yml
+++ b/.github/workflows/main.sonar.yml
@@ -29,20 +29,24 @@ jobs:
           aws-region: eu-west-2
 
       - name: ⚙️ Configure Codeartifact
-        run: aws codeartifact login --tool npm --repository registry-prod-repo --domain registry-prod --domain-owner ${{ secrets.AWS_CODEARTIFACT_ACCOUNT_ID }} --region eu-west-2
+        run: aws codeartifact login --tool pnpm --repository registry-prod-repo --domain registry-prod --domain-owner ${{ secrets.AWS_CODEARTIFACT_ACCOUNT_ID }} --region eu-west-2
+
+      - name: ⚙️ Setup pnpm
+        uses: pnpm/action-setup@v4
 
       - name: ⚙️ Setup Node.js
         uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
         with:
           node-version-file: '.node-version'
+          cache: 'pnpm'
 
       - name: ⚙️ Install Dependencies
-        run: npm ci
+        run: pnpm install --frozen-lockfile
 
       # Generate coverage
       - name: 🧪 Run Unit tests
         id: unittests
-        run: npm run test:coverage || echo "Failed to meet the criteria"
+        run: pnpm run test:coverage || echo "Failed to meet the criteria"
 
       # Perform scan
       - name: 🕵🏻 Run SonarQube Scan
