feat(NOT-19): Integrating with OTEL (#29)
* feat(NOT-19): Integrating with OTEL, adding unit tests to CICD

* fix(NOT-19): Attempting to add a coverage comment

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -4,14 +4,22 @@ on:
   # Trigger the workflow on pull request
   pull_request
 
+permissions:
+  contents: write
+  issues: write
+  pull-requests: write
+
 jobs:
   pr:
     runs-on: ubuntu-latest
     timeout-minutes: 60
-
     steps:
+      # Setup
       - name: Checkout Code
         uses: actions/checkout@v6
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
 
       - name: Setup Node.js
         uses: actions/setup-node@v6
@@ -21,26 +29,52 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
+      # Formatting
       - name: Run Lint Script
         run: npm run format
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
 
       - name: Terraform Formatting
         id: fmt
         run: terraform fmt -check
 
+      # Testing
+      - name: Run Unit tests
+        id: unittests
+        run: |
+          echo "Test results:" > coverage.md
+          echo '```' >> coverage.md
+          (npm run test:coverage 2>&1 | grep -A1000 "= Coverage summary =" | tee -a coverage.md) || echo "Failed to meet the criteria"
+          echo '```' >> coverage.md
+          content="${content//'%'/'%25'}"
+          content="${content//$'\n'/'%0A'}"
+          content="${content//$'\r'/'%0D'}"
+
+          echo 'report<<EOF' >> $GITHUB_OUTPUT
+          cat coverage.md >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+      - name: Create Comment with Test results
+        uses: hasura/comment-progress@v2.3.0
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          repository: 'govuk-once/gds-unified-notification-service'
+          number: ${{ github.event.number }}
+          id: unittestscomment
+          message: '${{steps.unittests.outputs.report}}'
+          recreate: true
+
+      # Security scans - Always executed even if the formatting or tests fail
       - name: TF Sec
+        if: success() || failure()
         uses: aquasecurity/tfsec-action@v1.0.0
 
       - name: Checkov GitHub Action
+        if: success() || failure()
         uses: bridgecrewio/checkov-action@v12
         with:
           output_format: cli,sarif
           output_file_path: console,results.sarif
           soft_fail: true
-        
+
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v4
         if: success() || failure()
