fix(NOT-19): Attempting to add a coverage comment

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -4,11 +4,15 @@ on:
   # Trigger the workflow on pull request
   pull_request
 
+permissions:
+  contents: write
+  issues: write
+  pull-requests: write
+
 jobs:
   pr:
     runs-on: ubuntu-latest
     timeout-minutes: 60
-
     steps:
       # Setup
       - name: Checkout Code
@@ -35,7 +39,28 @@ jobs:
 
       # Testing
       - name: Run Unit tests
-        run: npm run test:coverage
+        id: unittests
+        run: |
+          echo "Test results:" > coverage.md
+          echo '```' >> coverage.md
+          (npm run test:coverage 2>&1 | grep -A1000 "= Coverage summary =" | tee -a coverage.md) || echo "Failed to meet the criteria"
+          echo '```' >> coverage.md
+          content="${content//'%'/'%25'}"
+          content="${content//$'\n'/'%0A'}"
+          content="${content//$'\r'/'%0D'}"
+
+          echo 'report<<EOF' >> $GITHUB_OUTPUT
+          cat coverage.md >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+      - name: Create Comment with Test results
+        uses: hasura/comment-progress@v2.3.0
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          repository: 'govuk-once/gds-unified-notification-service'
+          number: ${{ github.event.number }}
+          id: unittestscomment
+          message: '${{steps.unittests.outputs.report}}'
+          recreate: true
 
       # Security scans - Always executed even if the formatting or tests fail
       - name: TF Sec
