feat(NOT-19): Integrating with OTEL, adding unit tests to CICD

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -10,8 +10,12 @@ jobs:
     timeout-minutes: 60
 
     steps:
+      # Setup
       - name: Checkout Code
         uses: actions/checkout@v6
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
 
       - name: Setup Node.js
         uses: actions/setup-node@v6
@@ -21,26 +25,31 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
+      # Formatting
       - name: Run Lint Script
         run: npm run format
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
 
       - name: Terraform Formatting
         id: fmt
         run: terraform fmt -check
 
+      # Testing
+      - name: Run Unit tests
+        run: npm run test:coverage
+
+      # Security scans - Always executed even if the formatting or tests fail
       - name: TF Sec
+        if: success() || failure()
         uses: aquasecurity/tfsec-action@v1.0.0
 
       - name: Checkov GitHub Action
+        if: success() || failure()
         uses: bridgecrewio/checkov-action@v12
         with:
           output_format: cli,sarif
           output_file_path: console,results.sarif
           soft_fail: true
-        
+
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v4
         if: success() || failure()
